#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling and Linting your project before committing'

npm run lint-staged ||
(
    echo '
❌ Check Failed. ❌
Make the changes required above.
'
    false;
)